@startuml
skinparam classAttributeIconSize 0

package "workbench" {
  class Workbench
  class WorkbenchRenderer
  class WorkbenchCommandController
  class LayoutManager
  class WorkbenchConfig

  class TitleBarPart
  class StatusBarPart
  class ActivityBarPart
  class PrimarySidebarPart
  class SecondarySidebarPart
  class PanelPart
  class EditorAreaPart
}

package "services" {
  class ServiceCollection
  interface IActivityBarService
  interface IPrimarySidebarService
  interface ISecondarySidebarService
  interface IPanelService
  interface IEditorAreaService
  interface ITitleBarService
  interface INotificationService
  interface ILayoutService
  interface IViewRegistry
}

package "command" {
  class CommandService
  enum CommandId
}

Workbench *-- ServiceCollection
Workbench *-- WorkbenchRenderer
Workbench *-- WorkbenchCommandController
Workbench *-- LayoutManager
Workbench *-- WorkbenchConfig
Workbench *-- TitleBarPart
Workbench *-- StatusBarPart
Workbench *-- ActivityBarPart
Workbench *-- PrimarySidebarPart
Workbench *-- SecondarySidebarPart
Workbench *-- PanelPart
Workbench *-- EditorAreaPart

WorkbenchRenderer --> ServiceCollection
WorkbenchRenderer --> LayoutManager
WorkbenchRenderer --> WorkbenchConfig
WorkbenchRenderer --> WorkbenchCommandController
WorkbenchRenderer --> TitleBarPart
WorkbenchRenderer --> StatusBarPart
WorkbenchRenderer --> ActivityBarPart
WorkbenchRenderer --> PrimarySidebarPart
WorkbenchRenderer --> SecondarySidebarPart
WorkbenchRenderer --> PanelPart
WorkbenchRenderer --> EditorAreaPart

TitleBarPart --> ITitleBarService
StatusBarPart --> INotificationService
ActivityBarPart --> IActivityBarService
PrimarySidebarPart --> IPrimarySidebarService
SecondarySidebarPart --> ISecondarySidebarService
PanelPart --> IPanelService
EditorAreaPart --> IEditorAreaService

ServiceCollection ..> IActivityBarService : provides
ServiceCollection ..> IPrimarySidebarService
ServiceCollection ..> ISecondarySidebarService
ServiceCollection ..> IPanelService
ServiceCollection ..> IEditorAreaService
ServiceCollection ..> ITitleBarService
ServiceCollection ..> INotificationService
ServiceCollection ..> ILayoutService
ServiceCollection ..> IViewRegistry

WorkbenchCommandController --> CommandService
WorkbenchCommandController --> ITitleBarService
WorkbenchCommandController --> INotificationService
WorkbenchCommandController --> IPanelService
WorkbenchCommandController --> IActivityBarService
WorkbenchCommandController --> IEditorAreaService
WorkbenchCommandController --> ILayoutService
WorkbenchCommandController --> ISecondarySidebarService

CommandService ..> CommandId
@enduml
